### ISSUE TITLE
iedriver3.5.1 can`t found IEDriverServer.exe file

### ISSUE THREAD

**Issue by imzengyang** [barretts/node-iedriver#13]
while i using the iedriver@3.5.1 with the javascript code like this
```
require("iedriver");
var webdriver=require('selenium-webdriver');
var driver =new webdriver.Builder().forBrowser("ie").build();
driver.get("http://www.baidu.com");
```
and i get an Error:
```
Error: IEDriverServer.exe could not be found on the current PATH. Please download the latest version of IEDriverServer.exe from http://sel
enium-release.storage.googleapis.com/index.html and ensure it can be found on your system PATH.
```

while i use the iedriver@3.4.0 is ok. i think 3.5.1 has a bug.

**Comment by koreyconway** [comment]
+1

I get the same. The zip files are downloaded but it seems they are not being unzipped.

**Comment by ghost** [comment]
Successfully unzipped for x64 platform (Windows 10) during "npm install" but it works with iedriver for 32 bit version that is still zipped. 
Found that when unzipped 32bit version - webdriver successfully initialized

**Comment by gtdminh** [comment]
i had a PR for this issue

**Comment by saibtech** [comment]
+1

**Comment by kay-ramme** [comment]
+1
