### ISSUE TITLE
Update npmconf@0.0.24 to npmconf@2.0.9

### ISSUE THREAD

**Issue by ceastman-ibm** [barretts/node-iedriver#18]
snyk test iedriver@3.9.2

Testing iedriver@3.9.2...
✗ Medium severity vulnerability found on semver@1.1.4
- desc: Regular Expression Denial of Service (DoS)
- info: https://snyk.io/vuln/npm:semver:20150403
- from: iedriver@3.9.2 > npmconf@0.0.24 > semver@1.1.4
Upgrade direct dependency npmconf@0.0.24 to npmconf@2.0.9 (triggers upgrades to semver@4.3.2)

**Comment by barretts** [comment]
fixed in 3.14.1!
