### ISSUE TITLE
Upgrade to 3.13

### ISSUE THREAD

**Issue by st-schaefer** [barretts/node-iedriver#19]
The current version of the iedriver executable is 3.13 but this package installs 3.9 Could you update the version numbers, please?

exports.binaryversion = '3.13.0';
exports.version = '3.13';

Thanks!

**Comment by mp-marc** [comment]
+1 to the above please, thanks.

**Comment by triforcecoin** [comment]
published, sorry I missed this ages ago

**Comment by barretts** [comment]
published, sorry I missed this ages ago
