### ISSUE TITLE
ie64driver

### ISSUE THREAD

**Issue by phillipgreenii** [barretts/node-iedriver#2]
Your wrapper has been working great for us, but we are getting slammed with problems that require us to update to use the 64 bit driver.  I thought about forking your projects and creating `ie64driver`, but I wanted to run it by you first.  Or perhaps you have a cleaner solution?

**Comment by phillipgreenii** [comment]
I created https://www.npmjs.com/package/ie64driver which is a fork of your code but downloads the 64 bit version of the driver.  I have no problem merging this back into your code base and giving you the ie64driver npm package.  Just let me know how to proceed.

**Comment by barretts** [comment]
Sorry this flew under my radar. In the not to distant past I ran into an issue where the 64 bit version would take a ridiculously long time to take any action. I mean 1 second per keystroke. Though I see value in being able to choose selectively between the two. I assume you haven't run into any such slow performance issues?

**Comment by phillipgreenii** [comment]
I had, which is why I forked your project.  I think the lag happens
whenever the bit versions don't match.  It has been a couple months since I
did this, so I don't remember the details.

**Comment by barretts** [comment]
I thought of a way to add the 64 bit version, just download both! Would that work for your need too?

**Comment by barretts** [comment]
Added it in https://github.com/barretts/node-iedriver/commit/e224f9fbb97f799383924b04bd333335d144a9cf
