### ISSUE TITLE
Update versions of dependencies adm-zip and npmconf

### ISSUE THREAD

**Issue by ShailyAggarwalK** [barretts/node-iedriver#20]
I am getting 3 vulnerabilities[1 high, 2 moderate] in my project when using iedriver@3.13.0

![image](https://user-images.githubusercontent.com/7420535/51521633-2dba2600-1e4d-11e9-90c4-ee0c4b2ff151.png)

![image](https://user-images.githubusercontent.com/7420535/51521612-1844fc00-1e4d-11e9-9ada-01fb1ab406b7.png)

Requesting update of adm-zip@0.2.1 to adm-zip@0.4.13
and as per 
[https://www.npmjs.com/package/npmconf](url)
npmconf is deprecated, thus generating high vulnerability. Can this be removed?

**Comment by barretts** [comment]
I honestly have not had any time to look into updating or removing those dependencies. If you have time please feel free to dig in and submit a pull request. Otherwise I'll eventually get around to it someday. Thank you!

**Comment by Danielwzl** [comment]
hi, I got same issue, can I get permisson to send a PR please?

**Comment by barretts** [comment]
@Danielwzl yes please submit a PR and I'll be happy to get it in.

**Comment by lotosotol** [comment]
Yep, this is valid, I have these same issues. Version 3.6.0 of the iedriver-exe.

**Comment by barretts** [comment]
Should be fixed for 3.14.0 now
