### ISSUE TITLE
`ReferenceError: response is not defined`

### ISSUE THREAD

**Issue by spalger** [barretts/node-iedriver#26]
https://github.com/barretts/node-iedriver/blob/66205b490a172da5f6f33fe207be63ee180d0d88/install.js#L127

On this line the `response` is being referenced which is not defined anywhere in the file.

**Comment by barretts** [comment]
Looks like a legit problem. Would you create a PR to fix it?

**Comment by spalger** [comment]
Would you be opposed to a removal of request and replacement with something like axios?

**Comment by spalger** [comment]
I'm really unsure about how I'd even fix this with request, and the request docs don't have a lot to say about the error event. Also there are the fun "this library is deprecated" warnings everywhere.

**Comment by barretts** [comment]
I don't have any attachment to request. If nothing breaks axios is good.

**Comment by spalger** [comment]
I think proxy support is the biggest feature that request has which hasn't been well supported by other libraries I've seen. Reading https://github.com/request/request#proxies and then looking at the implementation in Axios I don't think that https proxy support will be maintained if I was to move to Axios.

Considering that I'm going to dig deeper to figure out how to do this with request.

**Comment by spalger** [comment]
Oi, I was really overthinking this and just submitted #30 to just log the whole `err` variable.

**Comment by barretts** [comment]
Looks great thanks! Merged and published a new version to NPM
